-- 0022_ad_hoc_market_closures.up.sql
-- Mark the eleven days in 1990-2028 when the US market did not open for a reason
-- no annual rule predicts.
--
-- What was wrong
-- --------------
-- ref.trading_calendar is generated by fafnir.db.seed.trading_days as "weekdays
-- minus the recurring NYSE holidays". State funerals, Hurricane Sandy and the
-- September 11 closure are none of those, so all eleven dates were generated as
-- open sessions. ops.dq check_gaps asks the calendar what a session was, found no
-- bar for any security on any of them, and wrote 69,229 flags across 16,569
-- securities -- about 10% of the entire DQ queue, describing eleven days on which
-- the warehouse was correct and the calendar was not.
--
-- Why UPDATE and not DELETE
-- -------------------------
-- Recurring holidays are represented by ABSENCE: seed_calendar inserts open days
-- only, so before this migration every row in the table had is_open = TRUE and the
-- column had never once been used. Absence cannot distinguish "the market was
-- shut" from "the calendar was never generated for that year", and for a closure
-- we positively know about, the second reading is wrong. is_open = FALSE is what
-- the column is for, it keeps the row as evidence, and it is reversible -- which a
-- DELETE of reference data is not. Both readings satisfy the consumers: every
-- query that reads this table (check_gaps, check_freshness) already filters on
-- `AND is_open`.
--
-- This migration is one half of the fix and cannot be the whole of it
-- ------------------------------------------------------------------
-- It corrects rows that already exist. On a FRESH install migrations run before
-- `fafnir db seed`, so this UPDATE touches an empty table and the seed then
-- regenerates all eleven as open. The generator itself has to know, which is
-- fafnir.db.seed.AD_HOC_CLOSURES in the same change. Neither half is sufficient:
-- this one fixes deployed warehouses, that one fixes new ones.
--
-- The list is duplicated between here and AD_HOC_CLOSURES on purpose. A migration
-- is a frozen historical artifact and must not change meaning when the Python
-- constant is next edited; test_ad_hoc_closures_match_migration pins the two
-- together instead.
--
-- Applies to all five seeded US exchanges. These were market-wide closures, not
-- venue-specific halts. BATS did not exist before 2008 and OTC is a pseudo-venue,
-- but seed_calendar generates every exchange over the full range, so their rows
-- exist and would otherwise keep claiming sessions that no US venue held.

BEGIN;

UPDATE ref.trading_calendar
   SET is_open = FALSE
 WHERE is_open
   AND trade_date IN (
        DATE '1994-04-27',  -- Richard Nixon, national day of mourning
        DATE '2001-09-11',  -- September 11 attacks; reopened Monday the 17th
        DATE '2001-09-12',
        DATE '2001-09-13',
        DATE '2001-09-14',
        DATE '2004-06-11',  -- Ronald Reagan, national day of mourning
        DATE '2007-01-02',  -- Gerald Ford, national day of mourning
        DATE '2012-10-29',  -- Hurricane Sandy, two consecutive sessions
        DATE '2012-10-30',
        DATE '2018-12-05',  -- George H. W. Bush, national day of mourning
        DATE '2025-01-09'   -- Jimmy Carter, national day of mourning
   );

COMMIT;
